# Let's be optimistic
AllCops:
  NewCops: enable

# Metrics are best left for humans to decide
Metrics:
  Enabled: false

# Let's not encourage massive amounts of indentation and wasted space
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
# I feel like I 'lose' the end parens otherwise
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line
# I find this much easier to read
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
 

# These are just noisy and annoying
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
