# Metrics are best left for humans to decide
Metrics:
  Enabled: false

# These are just noisy and annoying
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false

# I find this much easier to read
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
